### ISSUE TITLE
How's the coffee?

### ISSUE THREAD

**Issue by E3V3A** [evilsocket/coffee#1]
Great and inspiring mini project! 

Apart from the obvious question: 
- What does the other *missing*  status values 0x02 and 0x03 do? (Are there more?)

and the huge concern:
- If we mess with the firmware upload, can we put the coffee maker on fire!?

But, most importantly: **How is the coffee?** (Was it a worth the investment? )

**Comment by evilsocket** [comment]
> What does the other missing status values 0x02 and 0x03 do? (Are there more?)

Honestly, I don't really remember, it's been a while since I don't look at this stuff :)

> If we mess with the firmware upload, can we put the coffee maker on fire!?

Yes

> How is the coffee?

Despite many bad reviews of this coffee machine, I really like the coffee it makes :)
